services:
  # trigger execution
  eblick_contao_trigger.listener.trigger:
    class: 'EBlick\ContaoTrigger\EventListener\TriggerListener'
    arguments:
    - '@eblick_contao_trigger.component.component_manager'
    - '@database_connection'
    - '@logger'
    - '@eblick_contao_trigger.execution.context_factory'
    - '@request_stack'
    public: true
    tags:
      - { name: 'contao.cronjob', interval: 'minutely', method: 'onExecute'}

  # data container
  eblick_contao_trigger.listener.datacontainer.common:
    class: 'EBlick\ContaoTrigger\EventListener\DataContainer\Common'
    tags:
      - { name: 'contao.callback', table: 'tl_eblick_trigger', target: 'config.onload', method: 'addBackendCss'}
      - { name: 'contao.callback', table: 'tl_eblick_trigger_log', target: 'config.onload', method: 'addBackendCss'}

  eblick_contao_trigger.listener.datacontainer.trigger:
    class: 'EBlick\ContaoTrigger\EventListener\DataContainer\Trigger'
    arguments:
    - '@eblick_contao_trigger.component.component_manager'
    - '@database_connection'
    - '@eblick_contao_trigger.listener.trigger'
    - '@contao.framework'
    tags:
      - { name: 'contao.hook', hook: 'loadDataContainer', method: 'onImportDefinitions'}
    public: true

  eblick_contao_trigger.listener.datacontainer.trigger_log:
    class: 'EBlick\ContaoTrigger\EventListener\DataContainer\ExecutionLog'
    public: true

  eblick_contao_trigger.listener.datacontainer.table_condition:
    class: 'EBlick\ContaoTrigger\EventListener\DataContainer\TableCondition'
    arguments:
    - '@database_connection'
    - '@eblick_contao_trigger.execution.row_data_compiler'
    - '@contao.framework'
    public: true

  eblick_contao_trigger.listener.datacontainer.notification_action:
    class: 'EBlick\ContaoTrigger\EventListener\DataContainer\NotificationAction'
    arguments:
    - '@eblick_contao_trigger.component.component_manager'
    - '@database_connection'
    public: true
