services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ['setFramework', ['@contao.framework']]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ['setContainer', ['@service_container']]

  # execution environment
  eblick_contao_trigger.execution.row_data_compiler:
    class: EBlick\ContaoTrigger\ExpressionLanguage\RowDataCompiler

  eblick_contao_trigger.execution.log:
    class: EBlick\ContaoTrigger\Execution\ExecutionLog
    arguments:
      - '@database_connection'

  eblick_contao_trigger.execution.context_factory:
    class: EBlick\ContaoTrigger\Execution\ExecutionContextFactory
    arguments:
      - '@eblick_contao_trigger.execution.log'

  # condition and action components
  eblick_contao_trigger.component.component_manager:
    class: EBlick\ContaoTrigger\Component\ComponentManager

  eblick_contao_trigger.component.table_condition:
    class: EBlick\ContaoTrigger\Component\Condition\TableCondition
    arguments:
     - '@database_connection'
     - '@eblick_contao_trigger.execution.row_data_compiler'
     - '@contao.framework'
    tags:
      - { name: eblick_contao_trigger.condition, alias: table }

  eblick_contao_trigger.component.time_condition:
    class: EBlick\ContaoTrigger\Component\Condition\TimeCondition
    arguments:
     - '@database_connection'
    tags:
      - { name: eblick_contao_trigger.condition, alias: time }

  eblick_contao_trigger.component.notification_action:
    class: EBlick\ContaoTrigger\Component\Action\NotificationAction
    arguments:
      - '@contao.framework'
    tags:
      - { name: eblick_contao_trigger.action, alias: notification }
